require('node:fs').mkdirSync('test-results', { recursive: true });
const { chromium } = require('C:/Users/parth/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({channel:'msedge',headless:true});
 const page = await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3000',{waitUntil:'networkidle'});
 assert.match(await page.title(),/Strategies Studio/);
 assert.equal(await page.locator('#services h3').count(),6);
 assert(!/Aster|Available balance|Open account/.test(await page.locator('body').innerText()));
 await page.getByRole('button',{name:'Services',exact:true}).click();
 assert(await page.locator('#service-menu').isVisible());
 await page.locator('#service-menu').getByText('Talent Acquisition',{exact:true}).click();
 assert.equal(await page.locator('#service-menu').count(),0);
 await page.getByRole('button',{name:'Find the real challenge'}).click();
 assert(await page.locator('#step-1').isVisible());
 assert(!(await page.locator('#step-0').isVisible()));
 const badAnchors=await page.locator('a[href^="#"]').evaluateAll(links=>links.map(l=>l.getAttribute('href')).filter(h=>!document.getElementById(h.slice(1))));
 assert.deepEqual(badAnchors,[]);
 for(const section of ['#services','#payroll','#approach','#why-us']) await page.locator(section).scrollIntoViewIfNeeded();
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'test-results/strategies-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.goto('http://localhost:3000',{waitUntil:'networkidle'});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.getByRole('button',{name:'Open navigation'}).click();
 await page.getByRole('navigation',{name:'Mobile navigation'}).getByText('About us',{exact:true}).click();
 assert.equal(await page.getByRole('navigation',{name:'Mobile navigation'}).count(),0);
 for(const section of ['#services','#payroll','#approach','#why-us']) await page.locator(section).scrollIntoViewIfNeeded();
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'test-results/strategies-mobile.png',fullPage:true});
 await page.goto('http://localhost:3000/dashboard',{waitUntil:'networkidle'});
 assert.match(page.url(),/\/#services$/);
 assert.deepEqual(errors,[]);
 console.log('PASS: source content, six services, desktop/mobile navigation, accordion, anchor links, no overflow, retired dashboard redirect, no runtime errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
