'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { Asterisk, House, ArrowLeftRight, CreditCard, Send, Settings2, Search, Bell, ChevronDown, Plus, ArrowUpRight, ArrowDownLeft, Download, X, Menu, LogOut, Check, SlidersHorizontal } from 'lucide-react';
import { motion, useReducedMotion } from 'framer-motion';
import { Button } from '@/components/ui/Button';
import { BentoCard } from '@/components/ui/BentoCard';
import { BalanceChart } from './BalanceChart';
import { TransactionTable } from './TransactionTable';
import { transactions, type Transaction } from '@/lib/data';
import { money } from '@/lib/utils';

type Section = 'Home' | 'Transactions' | 'Cards' | 'Payments' | 'Settings';
const navigation = [{ label: 'Home', icon: House }, { label: 'Transactions', icon: ArrowLeftRight }, { label: 'Cards', icon: CreditCard }, { label: 'Payments', icon: Send }] as const;
const field = 'mt-2 h-11 w-full rounded-md border border-line bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-gray-300';

export function Dashboard() {
  const [section, setSection] = useState<Section>('Home');
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All');
  const [rows, setRows] = useState<Transaction[]>(transactions);
  const [mobile, setMobile] = useState(false);
  const [notifications, setNotifications] = useState(false);
  const [switcher, setSwitcher] = useState(false);
  const [frozen, setFrozen] = useState(false);
  const [toast, setToast] = useState('');
  const [name, setName] = useState('Layers Studio');
  const search = useRef<HTMLInputElement>(null);
  const dialog = useRef<HTMLDialogElement>(null);
  const reduce = useReducedMotion();
  useEffect(() => { const handle = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key === 'k') { event.preventDefault(); search.current?.focus(); } if (event.key === 'Escape') { setNotifications(false); setSwitcher(false); setMobile(false); } }; window.addEventListener('keydown', handle); return () => window.removeEventListener('keydown', handle); }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4500); return () => clearTimeout(timer); }, [toast]);
  const filtered = rows.filter(row => `${row.description} ${row.category} ${row.detail}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All' || row.status === status));
  const navigate = (value: Section) => { setSection(value); setMobile(false); };
  // Native dialog handles focus trapping, Escape, and return focus for keyboard users.
  const submitPayment = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget); const amount = Number(data.get('amount'));
    if (!Number.isFinite(amount) || amount <= 0) return;
    setRows(previous => [{ id: crypto.randomUUID(), date: new Date().toISOString().slice(0, 10), description: String(data.get('recipient')), detail: 'Demo payment · no money moved', category: 'Transfer', amount: -amount, status: 'Pending' }, ...previous]);
    dialog.current?.close(); event.currentTarget.reset(); setToast('Demo payment added to recent activity.');
  };
  const exportCsv = () => {
    const csv = ['Date,Description,Category,Amount,Status', ...filtered.map(row => [row.date, row.description, row.category, row.amount, row.status].map(value => `"${String(value).replace(/"/g, '""')}"`).join(','))].join('\r\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); const link = document.createElement('a'); link.href = url; link.download = 'aster-transactions.csv'; link.click(); URL.revokeObjectURL(url); setToast('Transaction export downloaded.');
  };
  return <div className="min-h-screen lg:flex">
    {mobile && <button aria-label="Close sidebar" onClick={() => setMobile(false)} className="fixed inset-0 z-40 bg-black/20 lg:hidden" />}
    <aside className={`fixed inset-y-0 left-0 z-50 flex w-60 flex-col border-r border-line bg-[#f4f5f5] p-5 transition-transform lg:translate-x-0 ${mobile ? 'translate-x-0' : '-translate-x-full'}`}><div className="relative"><button onClick={() => setSwitcher(!switcher)} aria-expanded={switcher} className="flex w-full items-center gap-3 rounded-lg py-3 text-sm font-medium"><span className="rounded-lg bg-[#e6e9df] p-2"><Asterisk size={21} strokeWidth={1.5} /></span><span className="truncate">{name}</span><ChevronDown size={14} className="ml-auto" /></button>{switcher && <div className="absolute top-16 z-10 w-full rounded-lg border border-line bg-white p-2 shadow-crisp"><p className="px-3 py-2 text-xs text-muted">Demo workspace</p><button onClick={() => { setSwitcher(false); navigate('Settings'); }} className="w-full rounded-md p-3 text-left text-xs hover:bg-gray-50">Manage workspace →</button><Link href="/" className="flex items-center gap-2 p-3 text-xs"><LogOut size={13} />Back to website</Link></div>}</div><p className="mb-3 mt-9 px-3 text-[9px] uppercase tracking-[0.18em] text-muted">Workspace</p><nav aria-label="Dashboard" className="space-y-1">{navigation.map(({ label, icon: Icon }) => <button key={label} aria-current={section === label ? 'page' : undefined} onClick={() => navigate(label)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-[13px] transition ${section === label ? 'bg-white font-medium shadow-crisp' : 'text-muted hover:bg-white/60'}`}><Icon size={17} strokeWidth={1.5} />{label}{label === 'Payments' && <span className="ml-auto rounded bg-gray-200/70 px-1.5 text-[10px]">{rows.filter(row => row.status === 'Pending').length}</span>}</button>)}</nav><div className="mt-auto"><div className="mb-6 rounded-xl border border-line p-4"><p className="text-xs font-medium">A little room to explore.</p><p className="mt-2 text-[11px] leading-5 text-muted">You’re in a demo workspace.<br />Make yourself at home.</p><Link href="/" className="mt-3 inline-flex items-center gap-2 text-[11px]">Discover Aster<ArrowUpRight size={12} /></Link></div><button onClick={() => navigate('Settings')} className={`flex w-full items-center gap-3 rounded-lg p-3 text-xs ${section === 'Settings' ? 'bg-white' : 'text-muted'}`}><Settings2 size={16} strokeWidth={1.5} />Settings</button><div className="mt-5 flex items-center gap-3 border-t border-line pt-5"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#e4e8df] text-xs">JL</span><div><p className="text-xs font-medium">Jamie Lee</p><p className="mt-1 text-[10px] text-muted">Workspace admin</p></div><Link href="/" aria-label="Back to website" className="ml-auto"><LogOut size={14} className="text-muted" /></Link></div></div></aside>
    <div className="min-w-0 flex-1 lg:ml-60"><header className="flex h-20 items-center justify-between gap-3 border-b border-line bg-white px-5 md:px-10"><div className="flex items-center gap-3"><Button variant="ghost" aria-label="Open sidebar" onClick={() => setMobile(true)} className="!px-1 lg:hidden"><Menu size={20} /></Button><h1 className="text-sm font-medium">{section === 'Home' ? 'Overview' : section}</h1></div><div className="flex items-center gap-3 md:gap-5"><label className="flex h-9 items-center gap-2 rounded-md border border-line px-3"><Search size={14} strokeWidth={1.5} className="text-muted" /><input ref={search} aria-label="Search transactions" value={query} onChange={event => { setQuery(event.target.value); if (section !== 'Home') setSection('Transactions'); }} placeholder="Search anything..." className="w-24 bg-transparent text-xs outline-none sm:w-40" /><kbd className="hidden rounded border border-line px-1 text-[10px] text-muted sm:block">⌘ K</kbd></label><div className="relative"><button onClick={() => setNotifications(!notifications)} aria-label="Notifications" aria-expanded={notifications} className="relative p-2"><Bell size={18} strokeWidth={1.5} /><span className="absolute right-2 top-1.5 h-1 w-1 rounded-full bg-[#809579]" /></button>{notifications && <div className="absolute right-0 top-12 z-30 w-72 rounded-xl border border-line bg-white p-5 shadow-crisp"><h2 className="text-sm font-medium">You’re all caught up</h2><p className="mt-2 text-xs leading-5 text-muted">Your account activity is up to date. New alerts will appear here.</p></div>}</div></div></header>
      <motion.main key={section} initial={{ opacity: 0, y: reduce ? 0 : 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduce ? 0 : 0.25 }} className="mx-auto max-w-[1450px] p-5 md:p-10"><div className="mb-8 flex flex-wrap items-center justify-between gap-5"><div><p className="mb-2 text-[10px] uppercase tracking-[0.15em] text-muted">Tuesday, September 22, 2026</p><h2 className="text-2xl font-medium tracking-tight md:text-3xl">{section === 'Home' ? 'Good morning, Jamie' : section}<span className="ml-2 text-[#879778]">{section === 'Home' ? '✳' : ''}</span></h2><p className="mt-2 text-xs leading-6 text-muted">{section === 'Home' ? 'A clear view of your business. A little more peace of mind.' : 'Your financial workspace, thoughtfully connected.'}</p></div><Button onClick={() => dialog.current?.showModal()} size="sm"><Plus size={14} />Move money</Button></div>
      {section === 'Home' && <><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-[2fr_1fr_1fr]"><BentoCard className="min-w-0 !p-6 sm:col-span-2 xl:col-span-1"><div className="flex items-center justify-between text-xs text-muted">Available balance<ArrowUpRight size={15} strokeWidth={1.5} /></div><p className="mt-5 text-4xl font-medium tracking-heading md:text-[43px]">$248,520<span className="text-gray-400">.00</span></p><p className="mt-3 text-[10px] text-emerald-700">↗ 12.8% <span className="ml-1 text-muted">vs. last month</span></p><BalanceChart /><div className="flex justify-between text-[9px] text-muted"><span>Aug 24</span><span>Last 30 days</span><span>Sep 22</span></div></BentoCard>{[{ title: 'Total in', amount: 42850, icon: ArrowDownLeft, tint: 'bg-mint', foot: '24 incoming transactions' }, { title: 'Total out', amount: 18240, icon: ArrowUpRight, tint: 'bg-[#f4f0e7]', foot: '38 outgoing transactions' }].map(({ title, amount, icon: Icon, tint, foot }) => <BentoCard key={title} className="!p-6"><div className="flex justify-between"><span className={`flex h-9 w-9 items-center justify-center rounded-full ${tint}`}><Icon size={18} strokeWidth={1.5} /></span><span className="text-[10px] text-muted">This month</span></div><p className="mt-7 text-xs text-muted">{title}</p><p className="mt-3 text-[28px] font-medium tracking-tight">{money(amount)}</p><p className="mt-7 text-[10px] text-muted">{foot}</p></BentoCard>)}</div><div className="my-6 flex flex-wrap items-center gap-3 rounded-xl border border-[#e0e7dc] bg-[#f0f4ee] px-5 py-4"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-white"><Check size={13} className="text-[#748371]" /></span><p className="text-xs">Everything’s looking good.<span className="ml-2 text-muted">Your books are synced and your team is up to date.</span></p><button onClick={() => navigate('Settings')} className="ml-auto text-xs">View integrations ↗</button></div></>}
      {(section === 'Home' || section === 'Transactions' || section === 'Payments') && <div className="overflow-hidden rounded-xl border border-line bg-white"><div className="flex flex-wrap items-center justify-between gap-3 px-6 py-5"><h3 className="text-sm font-medium">{section === 'Payments' ? 'Payment activity' : 'Recent activity'}</h3><div className="flex items-center gap-3"><SlidersHorizontal size={13} className="text-muted" /><select aria-label="Filter transaction status" value={status} onChange={event => setStatus(event.target.value)} className="rounded-md border border-line bg-white px-2 py-2 text-[11px]"><option value="All">All statuses</option><option>Completed</option><option>Pending</option><option>Failed</option></select><Button variant="secondary" size="sm" onClick={exportCsv}><Download size={13} />Export</Button></div></div><TransactionTable rows={section === 'Payments' ? filtered.filter(row => row.amount < 0) : filtered} /><div className="border-t border-line px-6 py-4 text-[10px] text-muted">{(section === 'Payments' ? filtered.filter(row => row.amount < 0) : filtered).length} transactions · All amounts in USD · Demo data</div></div>}
      {section === 'Cards' && <div className="grid gap-6 md:grid-cols-2"><BentoCard><h3 className="text-sm font-medium">Your virtual card</h3><div className={`mx-auto my-8 max-w-sm rounded-2xl border border-gray-300 bg-[#dfe2d8] p-7 ${frozen ? 'opacity-50' : ''}`}><div className="flex justify-between"><Asterisk size={34} /><span className="text-xs">aster business</span></div><p className="mt-16 text-lg tracking-[0.25em]">•••• •••• •••• 8015</p><p className="mt-5 text-xs uppercase tracking-widest">Jamie Lee</p></div><div className="flex items-center justify-between"><span className="text-xs text-muted">{frozen ? 'Card frozen' : 'Active · Demo card'}</span><Button variant="secondary" size="sm" onClick={() => { setFrozen(!frozen); setToast(frozen ? 'Demo card unfrozen.' : 'Demo card frozen.'); }}>{frozen ? 'Unfreeze card' : 'Freeze card'}</Button></div></BentoCard><BentoCard><h3 className="text-sm font-medium">Monthly spending</h3><p className="mt-8 text-4xl tracking-heading">$3,480<span className="text-lg text-muted"> / $10,000</span></p><div role="meter" aria-label="Monthly spending" aria-valuenow={3480} aria-valuemin={0} aria-valuemax={10000} className="mt-6 h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full w-[34.8%] rounded-full bg-[#8a9b7f]" /></div><p className="mt-4 text-xs text-muted">$6,520 available this month</p></BentoCard></div>}
      {section === 'Settings' && <BentoCard className="max-w-2xl"><h3 className="text-lg font-medium">Workspace settings</h3><form onSubmit={event => { event.preventDefault(); setToast('Workspace name updated for this demo session.'); }} className="mt-6"><label className="text-xs text-muted">Workspace name<input required maxLength={40} value={name} onChange={event => setName(event.target.value)} className={field} /></label><p className="mt-6 text-xs text-muted">Connected integration</p><div className="my-3 flex justify-between rounded-md border border-line p-4 text-sm">Accounting sync<span className="text-xs text-emerald-700">Connected · Demo</span></div><Button type="submit" className="mt-4">Save changes</Button><p className="mt-4 text-xs text-muted">Changes are temporary and reset on page reload.</p></form></BentoCard>}
      <p className="mt-8 text-center text-[10px] leading-5 text-gray-400">Aster is a product concept. All activity shown is illustrative. No real money moves.</p></motion.main>
    </div>
    <dialog ref={dialog} aria-labelledby="payment-title" className="m-auto w-[calc(100%-2rem)] max-w-md rounded-2xl border border-line bg-white p-7 text-ink shadow-crisp backdrop:bg-black/25"><div className="flex items-center justify-between"><h2 id="payment-title" className="text-xl font-medium tracking-tight">Move money</h2><Button variant="ghost" aria-label="Close payment dialog" onClick={() => dialog.current?.close()}><X size={17} /></Button></div><p className="mt-2 text-xs leading-6 text-muted">Create a simulated payment. No real money will move.</p><form onSubmit={submitPayment} className="mt-5 space-y-5"><label className="block text-xs">Recipient<input autoFocus required name="recipient" maxLength={80} placeholder="Company or person" className={field} /></label><label className="block text-xs">Amount (USD)<input required name="amount" type="number" min="0.01" max="248520" step="0.01" placeholder="0.00" className={field} /></label><Button type="submit" className="w-full">Create demo payment<ArrowUpRight size={14} /></Button></form></dialog>
    {toast && <div role="status" className="fixed bottom-6 left-1/2 z-[60] flex w-[calc(100%-2rem)] max-w-sm -translate-x-1/2 items-center gap-3 rounded-xl border border-line bg-white p-4 text-xs shadow-crisp"><Check size={16} className="shrink-0 text-emerald-700" />{toast}<button aria-label="Dismiss message" onClick={() => setToast('')} className="ml-auto"><X size={14} /></button></div>}
  </div>;
}
