'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { ArrowUpRight, ArrowDown, ArrowRight, Menu, X, Pause, Play } from 'lucide-react';
const World = dynamic(()=>import('./World'),{ssr:false});
const chapters=['Introduction','About us','HR services','Why us','Our approach','Contact'];
// Adapted from strategiesstudio.com/why-us.html. These are partnership principles, not client case studies.
const projects=[{name:'Your context comes first',type:'A strategy shaped around you',year:'01',description:'Your goals, culture, and stage of growth guide our recommendations. We take time to understand the organisation before shaping a people strategy that fits.',color:'silver'},{name:'Insight with empathy',type:'Evidence meets human judgement',year:'02',description:'People data and market insight inform our thinking. Listening to employees and leaders keeps every recommendation grounded in the people it affects.',color:'orange'},{name:'With you through delivery',type:'A partner in sustainable growth',year:'03',description:'We work alongside your team as plans become practice, adapting processes and building capabilities that can grow with your organisation.',color:'dark'}];
const services=[['01','HR Strategy & Advisory','People roadmaps, organisation design, and HR policies aligned with your business direction.'],['02','Talent Acquisition','Recruitment, leadership search, employer positioning, and workforce planning for your next stage.'],['03','Employee Engagement','Employee listening, recognition, manager support, and retention initiatives that strengthen workplace culture.'],['04','Training & Development','Role-based learning, leadership development, and practical skills programmes with measurable outcomes.'],['05','Compliance & Risk','HR audits, workplace policies, employee documentation, and PoSH advisory for stronger foundations.'],['06','Payroll & Benefits','Monthly payroll, benefits administration, compensation benchmarking, and salary structure design.']];
export default function Experience(){
 const [ready,setReady]=useState(false),[active,setActive]=useState(0),[menu,setMenu]=useState(false),[paused,setPaused]=useState(false),[variant,setVariant]=useState(0),[project,setProject]=useState<number|null>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 const onReady=useCallback(()=>setReady(true),[]);
 useEffect(()=>{const sections=document.querySelectorAll<HTMLElement>('.chapter');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setActive(Number((e.target as HTMLElement).dataset.chapter));}),{rootMargin:'-35% 0px -35% 0px'});sections.forEach(s=>observer.observe(s));return()=>observer.disconnect();},[]);
 useEffect(()=>{if(project!==null)dialog.current?.showModal();else dialog.current?.close();},[project]);
 useEffect(()=>{if(!menu)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[menu]);
 return <div className={`experience chapter-${active}`}>
  <a className="skip" href="#intro">Skip to content</a>
  <World variant={variant} paused={paused} onReady={onReady}/>
  <div className="ambient"/>
  <header className="site-header"><a className="brand-logo" href="#home" aria-label="Strategies Studio home"><img src="/strategies-logo-landscape.png" alt="Strategies Studio — Designing the workforce of tomorrow" width="1800" height="600"/></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#studio">About us</a><a href="#capabilities">Services <sup>06</sup></a><a href="#work">Why us</a><a className="contact-link" href="#contact">Let’s talk <ArrowUpRight size={16}/></a></nav><button className="menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
  {menu&&<nav className="mobile-nav" aria-label="Mobile navigation">{[['About us','studio'],['Services','capabilities'],['Why us','work'],['Our approach','approach'],['Contact','contact']].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}<ArrowUpRight/></a>)}</nav>}
  <main>
   <section className="chapter hero" id="home" data-chapter="0"><div className="hero-kicker"><span className="live-dot"/> DESIGNING THE WORKFORCE OF TOMORROW</div><div className="hero-title" id="intro"><h1>People move<br/><em>everything.</em></h1><div className="hero-bottom"><p>Strategising people. Strengthening businesses.<br/>Your next chapter starts with the right people.</p><a className="circle-link" href="#studio" aria-label="Meet your HR partner"><ArrowDown size={22}/></a></div></div><div className="object-label"><span className="crosshair">+</span> A NEW PERSPECTIVE<br/><span>01 — THE WORLD OF STRATEGIES</span></div><div className="hero-foot"><span>STRATEGY × PEOPLE × GROWTH</span><span>{ready?'MOVE TO EXPLORE. SCROLL TO DISCOVER.':'SHAPING YOUR EXPERIENCE…'} <ArrowDown size={12}/></span></div></section>
   <section className="chapter studio" id="studio" data-chapter="1"><div className="section-content right"><span className="eyebrow">01 / ABOUT STRATEGIES STUDIO</span><h2>Your people.<br/>Our shared<br/><em>direction.</em></h2><p>Our team brings senior HR experience across startups, growing companies, and established enterprises. We help leaders turn business ambitions into practical people decisions.</p><p>From understanding your challenges to putting solutions in place, we work as an extension of your leadership team.</p><div className="studio-stats"><div><strong>10+</strong><span>Years of HR expertise</span></div><div><strong>6</strong><span>Connected HR practices</span></div><div><strong>360°</strong><span>HR partnership</span></div></div><a className="text-link" href="#capabilities">Explore our services <ArrowDown size={16}/></a></div></section>
   <section className="chapter capabilities" id="capabilities" data-chapter="2"><div className="section-content"><span className="eyebrow">02 / SIX CONNECTED HR PRACTICES</span><h2>From hire<br/><em>to inspire.</em></h2><div className="service-list">{services.map(([n,title,desc])=><details key={n}><summary><small>{n}</small>{title}<span>+</span></summary><p>{desc}</p></details>)}</div></div></section>
   <section className="chapter work" id="work" data-chapter="3"><div className="work-head"><span className="eyebrow">03 / WHY STRATEGIES STUDIO</span><h2>A partner.<br/><em>In every sense.</em></h2><p>Expertise, care, and shared ownership.<br/>Explore what shapes our partnership.</p></div><div className="project-list">{projects.map((p,i)=><button key={p.name} className={`project-row ${variant===i?'selected':''}`} onMouseEnter={()=>setVariant(i)} onFocus={()=>setVariant(i)} onClick={()=>{setVariant(i);setProject(i);}}><span className="project-number">{p.year}</span><span className="project-name">{p.name}<small>{p.type}</small></span><span className={`material-swatch ${p.color}`}/><ArrowUpRight/></button>)}</div></section>
   <section className="chapter approach" id="approach" data-chapter="4"><div className="section-content right"><span className="eyebrow">04 / OUR APPROACH</span><h2>Listen closely.<br/>Move forward.<br/><em>Together.</em></h2><p>We begin with your goals, people, and constraints. Then we turn insight into a workable plan, support delivery, and review progress against agreed measures.</p><ol className="process"><li><span>01</span> Understand your organisation.</li><li><span>02</span> Identify the underlying challenge.</li><li><span>03</span> Shape a practical solution.</li><li><span>04</span> Put the plan into practice together.</li><li><span>05</span> Track progress and refine.</li></ol></div></section>
   <section className="chapter contact" id="contact" data-chapter="5"><span className="eyebrow">05 / NEXT STARTS HERE</span><h2>Your next<br/><em>chapter.</em></h2><a className="big-cta" href="/contact/">Start a conversation<span><ArrowUpRight/></span></a><footer><a className="brand-logo" href="#home" aria-label="Strategies Studio home"><img src="/strategies-logo-landscape.png" alt="Strategies Studio" width="1800" height="600"/></a><p>People-centred HR.<br/>Business-focused progress.</p><span>© {new Date().getFullYear()} Strategies Studio</span><a href="#home">BACK TO TOP ↑</a></footer></section>
  </main>
  <aside className="chapter-indicator" aria-label="Journey navigation">{chapters.map((label,i)=><a key={label} aria-label={label} aria-current={active===i?'step':undefined} href={`#${['home','studio','capabilities','work','approach','contact'][i]}`}><span/>{active===i&&<small>{String(i+1).padStart(2,'0')}</small>}</a>)}</aside>
  <div className="scene-controls"><span className="live-dot"/><span>LIVE EXPERIENCE</span><button onClick={()=>setPaused(!paused)} aria-label={paused?'Play ambient animation':'Pause ambient animation'}>{paused?<Play size={12}/>:<Pause size={12}/>}</button></div>
  <dialog ref={dialog} className="project-dialog" onCancel={()=>setProject(null)} onClick={e=>{if(e.target===e.currentTarget)setProject(null);}}>{project!==null&&<article><button className="dialog-close" onClick={()=>setProject(null)} aria-label="Close project"><X/></button><span className="eyebrow">OUR PARTNERSHIP / {projects[project].year}</span><div className={`dialog-art ${projects[project].color}`}><div/></div><h2>{projects[project].name}</h2><p>{projects[project].description}</p><span className="project-note">STRATEGIES STUDIO · YOUR HR PARTNER</span><button className="text-link" onClick={()=>{setProject((project+1)%projects.length);setVariant((project+1)%projects.length);}}>Next principle <ArrowRight size={16}/></button></article>}</dialog>
 </div>;
}

