'use client';
import { useEffect, useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, ChevronDown, Menu, X, Compass, Users, HeartHandshake, GraduationCap, ShieldCheck, Wallet, Check, Plus, Minus, CircleDot } from 'lucide-react';
import { Brand } from '@/components/Brand';
import { BentoCard } from '@/components/ui/BentoCard';
import { Button } from '@/components/ui/Button';

const contact = '/contact';
const cta = 'inline-flex h-12 items-center justify-center gap-3 rounded-full bg-[#e4c58d] px-6 text-sm font-medium text-[#151c27] transition hover:bg-[#f1d6a8] active:scale-95 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4';
// Content adapted from Strategies Studio’s published services, about, and why-us pages.
const services = [
  { id: 'strategy', title: 'HR Strategy & Advisory', short: 'Strategy', icon: Compass, text: 'Connect business ambitions with a practical people roadmap. Bring clarity to roles, structure, culture, and HR processes.', tags: ['Organisation design', 'People strategy'], tone: 'bg-[#152333]' },
  { id: 'talent', title: 'Talent Acquisition', short: 'Talent', icon: Users, text: 'Build a stronger hiring journey, from workforce planning and executive search to candidate selection and onboarding.', tags: ['Executive search', 'Workforce planning'], tone: 'bg-[#262137]' },
  { id: 'engagement', title: 'Employee Engagement', short: 'Engagement', icon: HeartHandshake, text: 'Turn employee feedback into better everyday experiences through recognition, communication, and manager support.', tags: ['Culture', 'Retention'], tone: 'bg-surface' },
  { id: 'development', title: 'Training & Development', short: 'Learning', icon: GraduationCap, text: 'Develop confident leaders and capable teams with learning shaped around real roles and measurable performance.', tags: ['Leadership', 'Upskilling'], tone: 'bg-surface' },
  { id: 'compliance', title: 'Compliance & Risk', short: 'Compliance', icon: ShieldCheck, text: 'Strengthen your HR foundations with policy reviews, audits, workplace documentation, and PoSH advisory.', tags: ['HR audits', 'Workplace policies'], tone: 'bg-surface' },
  { id: 'payroll', title: 'Payroll & Benefits', short: 'Rewards', icon: Wallet, text: 'Support employee trust with reliable payroll operations, benefits administration, and informed compensation decisions.', tags: ['Payroll', 'Compensation'], tone: 'bg-[#30271e]' },
];
const steps = [
  { title: 'Understand your world', text: 'We start with your business priorities, people, and culture. A useful strategy begins with a clear understanding of the organisation it serves.' },
  { title: 'Find the real challenge', text: 'Conversations, observation, and people data help identify what is holding progress back.' },
  { title: 'Shape a practical plan', text: 'Together, we define solutions that fit your context and can be put into practice.' },
  { title: 'Put it into practice', text: 'Our team works alongside yours during implementation, adapting as your needs evolve.' },
  { title: 'Make progress visible', text: 'Agreed measures keep the work focused and help you understand its impact.' },
];
const links = [{ title: 'About us', href: '#about' }, { title: 'Why us', href: '#why-us' }, { title: 'Our approach', href: '#approach' }];

export function LandingPage() {
  const [scrolled, setScrolled] = useState(false);
  const [menu, setMenu] = useState(false);
  const [dropdown, setDropdown] = useState(false);
  const [step, setStep] = useState<number | null>(0);
  const reduce = useReducedMotion();
  useEffect(() => { const update = () => setScrolled(window.scrollY > 12); update(); window.addEventListener('scroll', update, { passive: true }); return () => window.removeEventListener('scroll', update); }, []);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') { setMenu(false); setDropdown(false); } }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []);
  const fade = { initial: { opacity: 0, y: reduce ? 0 : 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: reduce ? 0 : 0.6 } };
  return <>
    <a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:z-50 focus:bg-surface focus:p-4">Skip to content</a>
    {/* Existing minimalist navigation now leads to the consulting content. */}
    <header className={`sticky top-0 z-40 border-b transition-all ${scrolled ? 'border-gray-200 bg-white text-gray-900' : 'border-gray-200 bg-white text-gray-900'}`}><nav aria-label="Main navigation" className="mx-auto flex h-24 max-w-[1280px] items-center justify-between gap-5 px-6 lg:px-12"><Brand light /><div className="hidden items-center gap-7 text-[13px] lg:flex"><div className="relative"><button aria-expanded={dropdown} aria-controls="service-menu" onClick={() => setDropdown(!dropdown)} className="flex items-center gap-1.5 py-3">Services<ChevronDown size={12} className={dropdown ? 'rotate-180' : ''} /></button>{dropdown && <div id="service-menu" className="absolute left-0 top-12 w-64 rounded-xl border border-gray-200 bg-white p-2 shadow-crisp">{services.map(service => <a key={service.id} href={`#${service.id}`} onClick={() => setDropdown(false)} className="block rounded-lg px-4 py-3 text-xs hover:bg-gray-100">{service.title}</a>)}</div>}</div>{links.map(link => <a key={link.href} href={link.href} className="hover:text-muted">{link.title}</a>)}</div><a href={contact} className={`${cta} hidden !h-10 !px-5 !text-xs lg:inline-flex`}>Let’s talk<ArrowUpRight size={13} /></a><Button variant="ghost" className="text-gray-900 hover:bg-gray-100 lg:hidden" aria-label={menu ? 'Close navigation' : 'Open navigation'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X size={21} /> : <Menu size={21} />}</Button></nav>{menu && <nav aria-label="Mobile navigation" className="space-y-1 border-t border-gray-200 bg-white p-5 lg:hidden">{[{ title: 'Services', href: '#services' }, ...links].map(link => <a key={link.href} onClick={() => setMenu(false)} href={link.href} className="block p-3 text-sm">{link.title}</a>)}<a href={contact} className={cta}>Let’s talk<ArrowRight size={14} /></a></nav>}</header>
    <main id="main">
      <section className="relative isolate overflow-hidden pt-12 text-center md:pt-16">
        <motion.div {...fade} className="mx-auto max-w-5xl px-6"><a href="#services" className="inline-flex items-center gap-2 rounded-full border border-line bg-surface px-3 py-1.5 text-[11px] text-gray-300"><span className="h-1.5 w-1.5 rounded-full bg-[#c5a56c]" />People-first thinking. Business-minded HR.<ArrowRight size={12} /></a><h1 className="mt-7 text-[43px] font-medium leading-[1.07] tracking-heading sm:text-[64px] lg:text-[76px]">Strategising people.<br /><span className="text-[#d9ba7e]">Strengthening businesses.</span></h1><p className="mx-auto mt-6 max-w-[490px] text-[15px] leading-7 text-muted">Thoughtful HR for organisations ready to grow.<br className="hidden sm:block" />From the people you hire to the culture you build,<br className="hidden sm:block" />we help turn your ambition into everyday progress.</p><div className="mt-8 flex flex-wrap items-center justify-center gap-6"><a href={contact} className={cta}>Start a conversation<ArrowUpRight size={15} strokeWidth={1.5} /></a><a href="#services" className="flex items-center gap-2 text-[13px] font-medium">Explore our services<ArrowRight size={14} /></a></div><p className="mt-4 text-[10px] tracking-wide text-muted">Your people. Your goals. A strategy shaped around both.</p></motion.div>
        {/* An editorial service map replaces the banking mockup without implying a client portal. */}
        <motion.div {...fade} className="relative mx-auto mt-16 max-w-[1080px] px-4 md:mt-20"><div className="absolute -inset-x-8 bottom-4 top-20 -z-10 rounded-[50%] bg-[#293b58] blur-3xl" /><div className="overflow-hidden rounded-2xl border border-line bg-surface text-left"><div className="flex items-center justify-between gap-4 border-b border-line px-6 py-5 md:px-8"><span className="text-xs font-medium">Your people. The bigger picture.</span><span className="hidden items-center gap-2 rounded-full bg-[#152333] px-3 py-1.5 text-[10px] text-[#d9ba7e] sm:inline-flex"><span className="h-1 w-1 rounded-full bg-current" />A connected HR partnership</span></div><div className="grid md:grid-cols-[1.1fr_1.6fr]"><div className="border-b border-line bg-[#142131] p-6 md:border-b-0 md:border-r md:p-8"><span className="text-[9px] uppercase tracking-[0.17em] text-muted">The starting point</span><h2 className="mt-6 text-3xl font-medium leading-[1.12] tracking-heading">Your ambition.<br /><span className="text-[#d9ba7e]">Our shared direction.</span></h2><p className="mt-4 max-w-xs text-xs leading-6 text-muted">An integrated view of your people priorities, from building your team to supporting its growth.</p><div className="mt-7 flex items-center gap-2 text-[10px] text-[#d9ba7e]"><CircleDot size={14} />Designed around your organisation</div></div><div className="p-6 md:p-8"><div className="mb-5 flex items-center justify-between"><h3 className="text-xs font-medium">Six areas. Working together.</h3><ArrowUpRight size={14} className="text-muted" /></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{services.map(({ short, id, icon: Icon }) => <a href={`#${id}`} key={id} className="rounded-xl border border-line px-4 py-5 transition hover:bg-[#182334]"><Icon size={21} strokeWidth={1.3} className="text-[#d9ba7e]" /><p className="mt-4 text-xs font-medium">{short}</p></a>)}</div><div className="mt-5 flex items-center gap-2 text-[10px] text-muted"><Check size={13} className="text-[#d9ba7e]" />From strategic direction to practical delivery.</div></div></div></div></motion.div>
      </section>
      {/* Only published experience figures; no invented clients or project outcomes. */}
      <section aria-label="Our experience" className="border-b border-line px-6 pb-14 pt-10"><p className="text-center text-[10px] uppercase tracking-[0.17em] text-muted">Experience that sees the whole picture</p><div className="mx-auto mt-9 grid max-w-4xl grid-cols-2 gap-y-8 md:grid-cols-4">{[{ number: '10+', label: 'Years of HR expertise' }, { number: '6', label: 'Core HR services' }, { number: '100%', label: 'Tailored solutions' }, { number: '360°', label: 'HR partnership' }].map(stat => <div key={stat.label} className="text-center"><p className="text-3xl font-medium tracking-heading">{stat.number}</p><p className="mt-2 text-[11px] text-muted">{stat.label}</p></div>)}</div></section>
      <section id="about" className="mx-auto grid max-w-[1160px] scroll-mt-28 gap-8 px-6 py-20 md:grid-cols-2 md:gap-20"><div><p className="text-[10px] font-medium uppercase tracking-[0.2em] text-[#d9ba7e]">Meet your HR partner</p><h2 className="mt-4 text-4xl font-medium leading-[1.12] tracking-heading md:text-[44px]">People at the heart.<br /><span className="text-[#d9ba7e]">Progress in mind.</span></h2></div><div className="text-sm leading-7 text-muted"><p>Strategies Studio brings experienced HR professionals together to help businesses build stronger people practices. Our work spans growing startups, established companies, and larger enterprises.</p><p className="mt-4">We connect your goals with practical action, working with your leadership team from the first assessment through implementation.</p><a href="#approach" className="mt-5 inline-flex items-center gap-2 text-xs font-medium text-ink">See how we work<ArrowRight size={14} /></a></div></section>
      <section id="services" className="mx-auto max-w-[1160px] scroll-mt-28 px-6 pb-20"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.2em] text-[#d9ba7e]">Six practices. One people picture.</p><h2 className="mt-4 text-4xl font-medium leading-[1.12] tracking-heading md:text-[46px]">From hire to inspire.<br />And everything in between.</h2></div><p className="max-w-xs text-sm leading-6 text-muted">Connected HR expertise, shaped around<br className="hidden md:block" /> your organisation’s next chapter.</p></div><div className="grid grid-cols-1 gap-5 md:grid-cols-3">{services.map((service, index) => <motion.div key={service.id} {...fade} className={index === 0 ? 'md:col-span-2' : index === 5 ? 'md:col-span-3' : ''}><BentoCard id={service.id} className={`flex h-full min-h-[275px] scroll-mt-28 flex-col ${service.tone}`}><div className="flex items-center justify-between"><service.icon size={25} strokeWidth={1.3} /><span className="text-[10px] text-muted">0{index + 1}</span></div><h3 className="mt-5 text-xl font-medium tracking-tight">{service.title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-muted">{service.text}</p><div className="mt-auto flex flex-wrap items-center gap-2 pt-7">{service.tags.map(tag => <span key={tag} className="rounded-md border border-white/10 bg-surface/5 px-2.5 py-1.5 text-[10px] text-muted">{tag}</span>)}<a href={contact} aria-label={`Discuss ${service.title}`} className="ml-auto rounded-full border border-white/15 p-2 transition hover:bg-surface"><ArrowUpRight size={15} strokeWidth={1.5} /></a></div></BentoCard></motion.div>)}</div></section>
      <section id="approach" className="scroll-mt-24 border-y border-line bg-[#152333]/60"><div className="mx-auto grid max-w-[1160px] gap-10 px-6 py-20 md:grid-cols-2 md:gap-20"><div><p className="text-[10px] uppercase tracking-[0.2em] text-[#d9ba7e]">A partnership, in practice</p><h2 className="mt-4 text-4xl font-medium leading-[1.12] tracking-heading md:text-[46px]">A clear direction.<br />A shared commitment.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-muted">A considered process that moves from understanding to action, with your team involved along the way.</p><div className="mt-8 inline-flex items-center gap-2 rounded-full border border-line bg-surface px-4 py-2 text-[11px]"><Check size={13} className="text-[#d9ba7e]" />With you through implementation</div></div><div>{steps.map((item, index) => <div key={item.title} className="border-b border-line"><h3><button aria-expanded={step === index} aria-controls={`step-${index}`} onClick={() => setStep(step === index ? null : index)} className="flex w-full items-center gap-4 py-5 text-left text-sm font-medium"><span className="text-[10px] text-[#d9ba7e]">0{index + 1}</span>{item.title}{step === index ? <Minus size={15} className="ml-auto" /> : <Plus size={15} className="ml-auto" />}</button></h3><div id={`step-${index}`} hidden={step !== index} className="pb-5 pl-8 text-sm leading-6 text-muted">{item.text}</div></div>)}</div></div></section>
      <section id="why-us" className="mx-auto max-w-[1160px] scroll-mt-28 px-6 py-20"><div className="mb-10 text-center"><p className="text-[10px] uppercase tracking-[0.2em] text-[#d9ba7e]">Why Strategies Studio</p><h2 className="mt-4 text-4xl font-medium tracking-heading md:text-[46px]">Expertise with a human perspective.</h2></div><div className="grid gap-5 md:grid-cols-3">{[{ title: 'Your context comes first.', body: 'We take time to understand your organisation before proposing a direction. The work is shaped around your needs.' }, { title: 'Evidence meets empathy.', body: 'People data and business insight inform our recommendations, while human judgement keeps them grounded.' }, { title: 'Built to keep growing.', body: 'We develop structures and capabilities that adapt as your business changes, staying involved as plans become practice.' }].map(item => <BentoCard key={item.title}><Check size={19} strokeWidth={1.5} className="text-[#d9ba7e]" /><h3 className="mt-5 text-lg font-medium tracking-tight">{item.title}</h3><p className="mt-3 text-sm leading-7 text-muted">{item.body}</p></BentoCard>)}</div><p className="mt-9 text-center text-[11px] leading-6 tracking-wide text-muted">Integrity · Empathy · Collaboration · Innovation · Excellence · Accountability</p></section>
      <section id="contact" className="mx-auto max-w-[1112px] scroll-mt-28 border-t border-line px-6 py-20 text-center"><p className="text-[10px] uppercase tracking-[0.2em] text-[#d9ba7e]">Your next chapter</p><h2 className="mt-5 text-4xl font-medium tracking-heading md:text-5xl">You set the destination.<br /><span className="text-[#d9ba7e]">Let’s build the way forward.</span></h2><p className="mx-auto mt-5 max-w-md text-sm leading-7 text-muted">Tell us where your organisation is today,<br />and where you want your people to take it.</p><a href={contact} className={`${cta} mt-8`}>Start a conversation<ArrowUpRight size={14} /></a></section>
    </main><footer className="border-t border-line"><div className="mx-auto grid max-w-[1160px] gap-9 px-6 py-12 md:grid-cols-[1.5fr_1fr_1.4fr]"><div><Brand /><p className="mt-5 text-xs leading-6 text-muted">People-centred HR.<br />Business-focused progress.</p></div><div><p className="mb-4 text-[10px] uppercase tracking-widest text-muted">The studio</p>{[...links, { title: 'Contact', href: contact }].map(link => <a key={link.href} href={link.href} className="mb-3 block text-xs hover:text-muted">{link.title}</a>)}</div><div><p className="mb-4 text-[10px] uppercase tracking-widest text-muted">Our expertise</p>{services.map(service => <a key={service.id} href={`#${service.id}`} className="mb-3 block text-xs hover:text-muted">{service.title}</a>)}</div></div><div className="mx-auto flex max-w-[1112px] flex-wrap justify-between gap-4 border-t border-line px-6 py-6 text-[10px] text-muted"><span>© {new Date().getFullYear()} Strategies Studio</span><a href="/contact">Get in touch ↗</a><a href="#main">Back to top ↑</a></div></footer>
  </>;
}





